[package]
name = "lavan"
version = "0.0.2-EXPERIMENTAL-SUBJECT-TO-BREAKING-CHANGES"
authors = ["Sabi <sabivtuber@proton.me>"]
description = "Lavan is a parser library"
license = "GPL-3.0"
license-file = "LICENSE"
repository = "https://github.com/sabivtuber/lavan"
edition = "2021"

[dependencies]
either = { version = "1.9.0", optional = true }

[features]
default = ["either"]
either = ["dep:either"]
